// Code generated by kk; DO NOT EDIT.

package config

import (
	"net/http"
	
	"github.com/gin-gonic/gin"
	"github.com/waler4ik/godogs-rest-project/internal/api"
	"github.com/waler4ik/godogs-rest-project/internal/endpoints/machines/data"
)

func ConfigureRouter(a *api.API) http.Handler {
	ge := gin.Default()
	ConfigureMiddleware(ge)
	data.ConfigureRouter(a, ge)
	ge.GET("/ws", func(c *gin.Context) {
		a.Ws.Handler(c.Writer, c.Request)
	})
	return ge.Handler()
}
