// Code generated by kk; DO NOT EDIT.

package config

import (
	"github.com/waler4ik/godogs-rest-project/internal/api"
)

func configureProvider(logger func(string, ...any), a *api.Provider) error {
	return nil
}
