// Code generated by kk; DO NOT EDIT.

package config

import (
	"net/http"
	
	"github.com/gin-gonic/gin"
	"github.com/waler4ik/godogs-rest-project/internal/api"
)

func ConfigureRouter(a *api.API) http.Handler {
	ge := gin.Default()
	ConfigureMiddleware(ge)
	return ge.Handler()
}
