// Code generated by kk; DO NOT EDIT.

package errors

import (
	"net/http"
)

type ErrorResponse struct {
	StatusText string `json:"status"`
	ErrorText  string `json:"error,omitempty"`
}

func New(httpCode int, err error) (int, *ErrorResponse) {
	return httpCode, &ErrorResponse{
		StatusText: http.StatusText(httpCode),
		ErrorText:  err.Error(),
	}
}
