// Code generated by kk; BUT FEEL FREE TO EDIT.

package data

// Datum is the type that is exchanged in the REST interface as a JSON object
type Datum struct {
	// Define JSON attributes here e.g.
	Payload string `json:"payload" binding:"required"`
}
