// Code generated by kk; DO NOT EDIT.

package websocket

import (
	"net/http"

	"github.com/waler4ik/godogs-rest-project/internal/broadcast"
)

type Websocket interface {
	broadcast.Broadcast
	Handler(http.ResponseWriter, *http.Request)
}
